import type { PuzzleId, Room, RoomId } from './types'

const ALL_BEFORE_FINAL: PuzzleId[] = ['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8']

export const ROOMS: Record<RoomId, Room> = {
  hall: {
    id: 'hall',
    name: '玄関ホール',
    floor: '1F',
    map: { x: 1, y: 3 },
    description: '高い天井にシャンデリアが揺れる。奥の扉には重そうな数字錠。',
    background: 'linear-gradient(180deg, #3b2a1e 0%, #5a3d28 55%, #2a1c12 56%, #3d2a1c 100%)',
    exits: [
      {
        dir: 'north',
        to: 'corridor',
        label: '廊下',
        requires: ['p1'],
        lockedText: '数字錠が掛かっている。',
      },
    ],
    hotspots: [
      {
        id: 'hall-lock',
        emoji: '🔒',
        name: '扉の数字錠',
        x: 32,
        y: 14,
        text: '真鍮の板に何か刻まれている。',
        puzzle: 'p1',
      },
      {
        id: 'hall-shoes',
        emoji: '👞',
        name: '靴箱',
        x: 18,
        y: 72,
        text: '使用人と家族の靴が並ぶ。名札にはサイズが書いてある。',
        evidence: 'shoes',
      },
      {
        id: 'hall-portrait',
        emoji: '🖼️',
        name: '伯爵の肖像画',
        x: 80,
        y: 30,
        text: '時任伯爵の肖像。胸元には青く輝く宝石「星の涙」が描かれている。',
      },
      {
        id: 'hall-umbrella',
        emoji: '☂️',
        name: '傘立て',
        x: 84,
        y: 74,
        text: '濡れた傘が1本。昨夜は21時ごろまで雨が降っていたらしい。',
      },
    ],
  },
  corridor: {
    id: 'corridor',
    name: '中央廊下',
    floor: '1F',
    map: { x: 1, y: 2 },
    description: '館の中心を貫く長い廊下。四方に扉、上り階段と下り階段がある。',
    background: 'linear-gradient(180deg, #2c2433 0%, #43364d 55%, #5b3a2b 56%, #3a2519 100%)',
    exits: [
      { dir: 'south', to: 'hall', label: '玄関ホール' },
      { dir: 'north', to: 'library', label: '図書室' },
      { dir: 'east', to: 'dining', label: '食堂' },
      {
        dir: 'west',
        to: 'study',
        label: '書斎',
        requires: ['p2'],
        lockedText: '書斎には鍵が掛かっている。鍵は誰が持っているのだろう。',
      },
      {
        dir: 'up',
        to: 'bedroom',
        label: '2階・伯爵の寝室',
        requires: ['p5'],
        lockedText: '階段の格子扉に鍵が掛かっている。合鍵は厨房にあるらしい。',
      },
      {
        dir: 'down',
        to: 'cellar',
        label: '地下室',
        requires: ['p8'],
        lockedText: '地下への扉は固く施錠されている。',
      },
    ],
    hotspots: [
      {
        id: 'corridor-vase',
        emoji: '🏺',
        name: '花瓶',
        x: 22,
        y: 62,
        text: '温室で育てた白いバラが活けてある。茎に赤土が付いている。',
      },
      {
        id: 'corridor-clock',
        emoji: '🕰️',
        name: '廊下の時計',
        x: 78,
        y: 36,
        text: '正確に時を刻んでいる。館の時計の手入れは執事の佐伯の仕事だそうだ。',
      },
    ],
  },
  study: {
    id: 'study',
    name: '書斎',
    floor: '1F',
    map: { x: 0, y: 2 },
    description: '事件現場。開け放たれた金庫と、止まった振り子時計。',
    background: 'linear-gradient(180deg, #1f2a24 0%, #2f4237 55%, #4a3322 56%, #2c1d12 100%)',
    exits: [{ dir: 'east', to: 'corridor', label: '中央廊下' }],
    hotspots: [
      {
        id: 'study-safe',
        emoji: '🗄️',
        name: '金庫',
        x: 22,
        y: 60,
        text: '扉は開いたまま。中は空だ。ダイヤルをよく見ると……',
        evidence: 'safe',
      },
      {
        id: 'study-desk',
        emoji: '📝',
        name: '机のメモ',
        x: 55,
        y: 70,
        text: '伯爵の走り書きが残されている。',
        puzzle: 'p3',
      },
      {
        id: 'study-clock',
        emoji: '⏱️',
        name: '振り子時計',
        x: 80,
        y: 32,
        text: '振り子が止まっている。扉は固く閉じていて、何か仕掛けがありそうだ。',
      },
    ],
  },
  library: {
    id: 'library',
    name: '図書室',
    floor: '1F',
    map: { x: 1, y: 1 },
    description: '壁一面の本棚。古い紙の匂いがする。',
    background: 'linear-gradient(180deg, #2b1f17 0%, #4a3324 55%, #2f241c 56%, #1c1510 100%)',
    exits: [
      { dir: 'south', to: 'corridor', label: '中央廊下' },
      { dir: 'east', to: 'music', label: '音楽室' },
    ],
    hotspots: [
      {
        id: 'library-books',
        emoji: '📚',
        name: '三冊の本',
        x: 50,
        y: 42,
        text: '赤・青・緑の3冊だけ、背表紙に手書きの言葉がある。',
        puzzle: 'p4',
      },
      {
        id: 'library-globe',
        emoji: '🌍',
        name: '地球儀',
        x: 18,
        y: 70,
        text: '甥の蓮がよく回して遊んでいるらしい。指紋だらけだ。',
      },
      {
        id: 'library-chair',
        emoji: '🪑',
        name: '読書椅子',
        x: 82,
        y: 70,
        text: '蓮は昨夜、21時から22時までここで一人で本を読んでいたと言う。証人はいない。',
      },
    ],
  },
  music: {
    id: 'music',
    name: '音楽室',
    floor: '1F',
    map: { x: 2, y: 1 },
    description: 'グランドピアノが一台。窓の向こうに温室のガラス屋根が見える。',
    background: 'linear-gradient(180deg, #1d2238 0%, #2f3760 55%, #3b2c25 56%, #241a15 100%)',
    exits: [
      { dir: 'west', to: 'library', label: '図書室' },
      {
        dir: 'east',
        to: 'greenhouse',
        label: '温室',
        requires: ['p4'],
        lockedText: '温室へのガラス戸は施錠されている。',
      },
    ],
    hotspots: [
      {
        id: 'music-piano',
        emoji: '🎹',
        name: 'ピアノ',
        x: 50,
        y: 58,
        text: '蓋に小さな数字錠。譜面台に楽譜が置かれている。',
        puzzle: 'p6',
      },
      {
        id: 'music-violin',
        emoji: '🎻',
        name: 'バイオリン',
        x: 16,
        y: 40,
        text: '弦が一本切れている。事件とは関係なさそうだ。',
      },
      {
        id: 'music-window',
        emoji: '🪟',
        name: '窓',
        x: 84,
        y: 34,
        text: '温室が見える。庭師の権田は昨夜、21時から22時まで庭の物置で道具の手入れをしていたと言う。証人はいない。',
      },
    ],
  },
  greenhouse: {
    id: 'greenhouse',
    name: '温室',
    floor: '1F',
    map: { x: 3, y: 1 },
    description: 'むせかえるような緑。床は雨水で湿った赤土だ。',
    background: 'linear-gradient(180deg, #1c3324 0%, #2f5a3a 55%, #6b3324 56%, #4a2216 100%)',
    exits: [{ dir: 'west', to: 'music', label: '音楽室' }],
    hotspots: [
      {
        id: 'greenhouse-pots',
        emoji: '🪴',
        name: '植木鉢',
        x: 50,
        y: 58,
        text: '3×3に並んだ鉢に番号札。いくつか抜け落ちている。',
        puzzle: 'p7',
      },
      {
        id: 'greenhouse-rose',
        emoji: '🌹',
        name: 'バラの花壇',
        x: 18,
        y: 40,
        text: '赤土の花壇。この館で赤土があるのは温室だけだ。',
      },
      {
        id: 'greenhouse-glove',
        emoji: '🧤',
        name: '園芸用手袋',
        x: 82,
        y: 74,
        text: '右手用だけがすり減っている。権田のものだろう。',
      },
    ],
  },
  dining: {
    id: 'dining',
    name: '食堂',
    floor: '1F',
    map: { x: 2, y: 2 },
    description: '晩餐の後片付けがまだ途中のようだ。長いテーブルに5つの椅子。',
    background: 'linear-gradient(180deg, #3a1f1f 0%, #5e3030 55%, #3d2a1c 56%, #261a11 100%)',
    exits: [
      { dir: 'west', to: 'corridor', label: '中央廊下' },
      { dir: 'east', to: 'kitchen', label: '厨房' },
    ],
    hotspots: [
      {
        id: 'dining-table',
        emoji: '🍽️',
        name: '長テーブル',
        x: 50,
        y: 60,
        text: '席札は片付けられてしまった。使用人たちの話から席順を推理できそうだ。',
        puzzle: 'p2',
      },
      {
        id: 'dining-candle',
        emoji: '🕯️',
        name: '燭台',
        x: 20,
        y: 36,
        text: '蝋燭は半分ほど燃え尽きている。',
      },
      {
        id: 'dining-wine',
        emoji: '🍷',
        name: 'ワイングラス',
        x: 82,
        y: 40,
        text: '1つだけ口紅の跡がある。メイドの小春のものだろう。',
      },
    ],
  },
  kitchen: {
    id: 'kitchen',
    name: '厨房',
    floor: '1F',
    map: { x: 3, y: 2 },
    description: 'パンの焼ける匂い。壁際に調味料の戸棚がある。',
    background: 'linear-gradient(180deg, #33302a 0%, #575044 55%, #6b6b6b 56%, #4a4a4a 100%)',
    exits: [{ dir: 'west', to: 'dining', label: '食堂' }],
    hotspots: [
      {
        id: 'kitchen-shelf',
        emoji: '🧂',
        name: '調味料の戸棚',
        x: 50,
        y: 40,
        text: '3桁のダイヤル錠。マルコのメモが貼ってある。',
        puzzle: 'p5',
      },
      {
        id: 'kitchen-oven',
        emoji: '🍞',
        name: 'オーブン',
        x: 20,
        y: 68,
        text: '焼き上がったパンが並んでいる。夜通し仕込んでいたらしい。',
      },
      {
        id: 'kitchen-knife',
        emoji: '🔪',
        name: '包丁立て',
        x: 82,
        y: 68,
        text: 'すべて右利き用の包丁だ。',
      },
    ],
  },
  bedroom: {
    id: 'bedroom',
    name: '伯爵の寝室',
    floor: '2F',
    map: { x: 1, y: 0 },
    description: '天蓋付きのベッド。窓からは時計塔が見える。',
    background: 'linear-gradient(180deg, #2a1f38 0%, #46345e 55%, #3b2a40 56%, #241a28 100%)',
    exits: [{ dir: 'down', to: 'corridor', label: '中央廊下' }],
    hotspots: [
      {
        id: 'bedroom-box',
        emoji: '💎',
        name: '宝石箱',
        x: 50,
        y: 60,
        text: '4桁の錠が付いている。蓋の裏に文字がある。',
        puzzle: 'p8',
      },
      {
        id: 'bedroom-diary',
        emoji: '📔',
        name: '日記',
        x: 20,
        y: 40,
        text: '伯爵の日記。誕生日のことが書いてある。',
      },
      {
        id: 'bedroom-window',
        emoji: '🗼',
        name: '窓の外の時計塔',
        x: 82,
        y: 32,
        text: '時計塔の大時計も 21時30分 で止まっている。',
      },
    ],
  },
  cellar: {
    id: 'cellar',
    name: '地下室',
    floor: 'B1',
    map: { x: 0, y: 3 },
    description: 'ひんやりとした石造りの部屋。奥に時計塔へ続く鉄扉。',
    background: 'linear-gradient(180deg, #151515 0%, #2b2b2b 55%, #3a3530 56%, #1f1c19 100%)',
    exits: [
      { dir: 'up', to: 'corridor', label: '中央廊下' },
      {
        dir: 'north',
        to: 'tower',
        label: '時計塔',
        requires: [...ALL_BEFORE_FINAL, 'p9'],
        lockedText: '鉄扉は閉ざされている。館の謎をすべて解いてからでないと開かないようだ。',
      },
    ],
    hotspots: [
      {
        id: 'cellar-scale',
        emoji: '⚖️',
        name: '天秤と金貨',
        x: 50,
        y: 58,
        text: '鉄扉の前に古い天秤と8枚の金貨。',
        puzzle: 'p9',
      },
      {
        id: 'cellar-wine',
        emoji: '🍾',
        name: 'ワイン棚',
        x: 18,
        y: 40,
        text: '埃をかぶったワインが並ぶ。一か所だけ埃が拭われている。',
      },
    ],
  },
  tower: {
    id: 'tower',
    name: '時計塔',
    floor: '塔',
    map: { x: 0, y: 0 },
    description: '巨大な歯車が止まったまま。関係者5人がここに集められている。',
    background: 'linear-gradient(180deg, #0f1a2e 0%, #23365e 55%, #4a3b2a 56%, #2b2218 100%)',
    exits: [{ dir: 'south', to: 'cellar', label: '地下室' }],
    hotspots: [
      {
        id: 'tower-gear',
        emoji: '⚙️',
        name: '大時計の歯車',
        x: 50,
        y: 40,
        text: '真実を告げる時が来た。',
        puzzle: 'p10',
      },
    ],
  },
}

/** 未施錠か、必要な謎をすべて解いていれば通れる */
export function canPass(requires: PuzzleId[] | undefined, solved: PuzzleId[]): boolean {
  return (requires ?? []).every((id) => solved.includes(id))
}
