import type { Room, RoomId } from '../../types'

/**
 * シナリオ 2「雪の天文台と消えた彗星」の部屋。
 * 部屋の物の説明文は、謎の問題文・証拠の文・solve.ts の PAINTINGS と食い違わないようにする
 * （星座の絵の署名と星の数、証拠の文は observatory.test.ts が照合する）。
 * 停電のあいだの明暗は q9 の手がかりで示すので、部屋の説明では書かない
 */
export const ROOMS: Record<RoomId, Room> = {
  entrance: {
    id: 'entrance',
    name: '玄関',
    floor: '1F',
    map: { x: 1, y: 3 },
    description: '雪の山荘「星見荘」の玄関。奥の扉の先が廊下だ。',
    background: 'linear-gradient(180deg, #1d2a40 0%, #36506f 55%, #1c2230 56%, #2a2f3a 100%)',
    exits: [{ dir: 'north', to: 'corridor', label: '廊下' }],
    hotspots: [
      {
        id: 'entrance-clock',
        emoji: '🕰️',
        name: '柱時計',
        x: 20,
        y: 62,
        text: '玄関の大きな柱時計。止まったまま、0時15分を指している。振り子の扉に 4桁の錠が掛かっている。',
        puzzle: 'q1',
      },
      {
        id: 'entrance-skis',
        emoji: '🎿',
        name: 'スキー板',
        x: 82,
        y: 36,
        text: '雪の付いたスキー板が 6組、壁に立て掛けてある。昨日の夕方から誰も外へ出ていない。',
      },
      {
        id: 'entrance-register',
        emoji: '📒',
        name: '来客名簿',
        x: 80,
        y: 74,
        text: '来客名簿。今夜の山荘にいるのは、助手の氷室、記者の早瀬、管理人の雪村、写真家の鳴海、研究員の真壁、博士の姪の灯の 6人。',
      },
    ],
  },
  corridor: {
    id: 'corridor',
    name: '廊下',
    floor: '1F',
    map: { x: 1, y: 2 },
    description: '山荘の中心を通る廊下。各部屋の扉と、上り階段・下り階段がある。',
    background: 'linear-gradient(180deg, #1a2338 0%, #2e3d5a 55%, #3a3340 56%, #231f2a 100%)',
    exits: [
      { dir: 'south', to: 'entrance', label: '玄関' },
      { dir: 'north', to: 'lounge', label: '談話室' },
      { dir: 'west', to: 'darkroom', label: '暗室' },
      { dir: 'east', to: 'kitchen', label: '厨房' },
      { dir: 'up', to: 'study', label: '2階・書斎' },
      { dir: 'down', to: 'storage', label: '地下倉庫' },
    ],
    hotspots: [
      {
        id: 'corridor-painting',
        emoji: '🖼️',
        name: '星空の油絵',
        x: 22,
        y: 62,
        text: '博士が描いた星空の油絵。星の並びが、どこか不自然だ。',
        puzzle: 'q6',
        concealed: true,
      },
      {
        id: 'corridor-window',
        emoji: '🪟',
        name: '窓',
        x: 78,
        y: 40,
        text: '外は一面の雪だ。雪は 21時半に降りはじめ、23時すぎに止んだと管理人が言っていた。',
      },
      {
        id: 'corridor-phone',
        emoji: '☎️',
        name: '内線電話',
        x: 78,
        y: 70,
        text: '山荘の部屋どうしを結ぶ内線電話。山道が雪でふさがれ、外とは連絡がつかない。',
      },
    ],
  },
  lounge: {
    id: 'lounge',
    name: '談話室',
    floor: '1F',
    map: { x: 1, y: 1 },
    description: '暖炉のある談話室。椅子が輪になって並んでいる。',
    background: 'linear-gradient(180deg, #2a2540 0%, #4a4a6e 55%, #4a3326 56%, #2a1d16 100%)',
    exits: [
      { dir: 'south', to: 'corridor', label: '廊下' },
      { dir: 'west', to: 'archive', label: '書庫' },
      { dir: 'east', to: 'dining', label: '食堂' },
    ],
    hotspots: [
      {
        id: 'lounge-chair',
        emoji: '🔥',
        name: '暖炉の前の椅子',
        x: 50,
        y: 56,
        text: '暖炉の前に椅子が並ぶ。ここで、停電のあいだの居場所を一人ずつ聞き取れそうだ。',
        puzzle: 'q2',
      },
      {
        id: 'lounge-cancer',
        emoji: '🦀',
        name: '蟹座の絵',
        x: 20,
        y: 38,
        text: '暖炉の上に掛かった蟹座の絵。隅に博士の署名がある。星が 5つ描かれている。',
      },
      {
        id: 'lounge-chess',
        emoji: '♟️',
        name: 'チェス盤',
        x: 82,
        y: 70,
        text: '対局の途中のまま、駒が並んでいる。',
      },
    ],
  },
  archive: {
    id: 'archive',
    name: '書庫',
    floor: '1F',
    map: { x: 0, y: 1 },
    description: '天井まで届く本棚が並ぶ書庫。古い紙の匂いがする。',
    background: 'linear-gradient(180deg, #1a2030 0%, #2f3f5a 55%, #2b2a33 56%, #1a1a22 100%)',
    exits: [{ dir: 'east', to: 'lounge', label: '談話室' }],
    hotspots: [
      {
        id: 'archive-aries',
        emoji: '🐏',
        name: '牡羊座の絵',
        x: 50,
        y: 38,
        text: '書庫の壁に掛かった牡羊座の絵。隅に博士の署名がある。星が 4つ描かれている。',
      },
      {
        id: 'archive-yearbooks',
        emoji: '📚',
        name: '天文年鑑の棚',
        x: 18,
        y: 66,
        text: '天文年鑑が並ぶ棚。一段だけ、本の並びが乱れている。',
      },
      {
        id: 'archive-desk',
        emoji: '🪑',
        name: '読書机',
        x: 80,
        y: 70,
        text: '氷室がよく使う机だ。',
      },
    ],
  },
  darkroom: {
    id: 'darkroom',
    name: '暗室',
    floor: '1F',
    map: { x: 0, y: 2 },
    description: '写真乾板を現像する小部屋。窓はない。',
    background: 'linear-gradient(180deg, #1a1018 0%, #3a2a3a 55%, #1e1a24 56%, #120e16 100%)',
    exits: [{ dir: 'east', to: 'corridor', label: '廊下' }],
    hotspots: [
      {
        id: 'darkroom-boxes',
        emoji: '📦',
        name: '乾板の箱',
        x: 50,
        y: 42,
        text: '棚に写真乾板の箱が 3つ並ぶ。管理人の雪村は「札は 3つとも、わざと違う箱に貼ってある」と言う。',
        puzzle: 'q3',
      },
      {
        id: 'darkroom-lamp',
        emoji: '🔴',
        name: '安全灯',
        x: 18,
        y: 38,
        text: '暗室で使う赤い安全灯。乾板を感光させない色の光で、現像の作業はこの下で行う。',
      },
      {
        id: 'darkroom-tray',
        emoji: '🧪',
        name: '現像の皿',
        x: 80,
        y: 70,
        text: '現像液の皿。中の乾板は、まだ濡れている。',
      },
    ],
  },
  dining: {
    id: 'dining',
    name: '食堂',
    floor: '1F',
    map: { x: 2, y: 1 },
    description: '長いテーブルのある食堂。壁に額が並ぶ。',
    background: 'linear-gradient(180deg, #1c2638 0%, #3d5470 55%, #3a2f2a 56%, #231c18 100%)',
    exits: [
      { dir: 'west', to: 'lounge', label: '談話室' },
      { dir: 'south', to: 'kitchen', label: '厨房' },
    ],
    hotspots: [
      {
        id: 'dining-keys',
        emoji: '🗝️',
        name: '鍵束',
        x: 50,
        y: 58,
        text: '管理人の鍵束が、テーブルに置き忘れてある。金・銀・銅・鉄・真鍮の 5本に札が付いている。',
        puzzle: 'q10',
      },
      {
        id: 'dining-libra',
        emoji: '⚖️',
        name: '天秤座の版画',
        x: 20,
        y: 36,
        text: '壁に掛かった天秤座の版画。隅に画家の署名がある。星が 7つ描かれている。',
      },
      {
        id: 'dining-candle',
        emoji: '🕯️',
        name: '燭台',
        x: 82,
        y: 40,
        text: '銀細工の古い燭台。',
      },
    ],
  },
  kitchen: {
    id: 'kitchen',
    name: '厨房',
    floor: '1F',
    map: { x: 2, y: 2 },
    description: '鍋や食器が並ぶ厨房。',
    background: 'linear-gradient(180deg, #2a323a 0%, #5a6a78 55%, #555b63 56%, #34383e 100%)',
    exits: [
      { dir: 'north', to: 'dining', label: '食堂' },
      { dir: 'west', to: 'corridor', label: '廊下' },
    ],
    hotspots: [
      {
        id: 'kitchen-cupboard',
        emoji: '🥛',
        name: '二つの升',
        x: 50,
        y: 40,
        text: '戸棚の上に、5デシリットルと 3デシリットルの升が置いてある。戸棚には 1桁の数字錠が掛かっている。',
        puzzle: 'q7',
      },
      {
        id: 'kitchen-clockcare',
        emoji: '📓',
        name: '管理人の手入れ帳',
        x: 20,
        y: 68,
        text: '壁に、管理人の手入れ帳が掛かっている。',
        evidence: 'clockcare',
      },
      {
        id: 'kitchen-pot',
        emoji: '☕',
        name: 'ココアの鍋',
        x: 82,
        y: 68,
        text: '鍋の底に、ココアが少し残っている。',
      },
    ],
  },
  study: {
    id: 'study',
    name: '書斎',
    floor: '2F',
    map: { x: 0, y: 0 },
    description: '博士の書斎。机と望遠鏡のほか、壁には絵が掛かっている。',
    background: 'linear-gradient(180deg, #16243a 0%, #2c4560 55%, #3d3228 56%, #221a14 100%)',
    exits: [
      { dir: 'down', to: 'corridor', label: '廊下' },
      { dir: 'east', to: 'guest', label: '客室' },
    ],
    hotspots: [
      {
        id: 'study-scope',
        emoji: '🔭',
        name: '望遠鏡の架台',
        x: 22,
        y: 38,
        text: '書斎の小さな望遠鏡。架台に 4桁の錠が付いていて、博士の走り書きが添えてある。',
        puzzle: 'q4',
      },
      {
        id: 'study-notebook',
        emoji: '📔',
        name: '博士の手帳',
        x: 55,
        y: 36,
        text: '机の上に、博士の手帳がある。最後のページにだけ、意味の通らない文字が並ぶ。',
        puzzle: 'q5',
      },
      {
        id: 'study-capricorn',
        emoji: '🐐',
        name: '山羊座の絵',
        x: 80,
        y: 34,
        text: '壁に掛かった山羊座の絵。隅に博士の署名がある。星が 8つ描かれている。',
      },
      {
        id: 'study-schedule',
        emoji: '📅',
        name: '観測会の予定表',
        x: 22,
        y: 68,
        text: '机の端に、予定表が置いてある。',
        evidence: 'stargazing',
      },
    ],
  },
  guest: {
    id: 'guest',
    name: '客室',
    floor: '2F',
    map: { x: 1, y: 0 },
    description: '来客用の客室。奥の扉が、ドームへ続く外階段につながっている。',
    background: 'linear-gradient(180deg, #1a2238 0%, #46587a 55%, #34303a 56%, #211e26 100%)',
    exits: [
      { dir: 'west', to: 'study', label: '書斎' },
      { dir: 'up', to: 'dome', label: '屋上・観測ドーム' },
    ],
    hotspots: [
      {
        id: 'guest-safe',
        emoji: '🔐',
        name: '金庫',
        x: 22,
        y: 60,
        text: '壁に埋め込まれた金庫。3桁の数字錠が掛かっている。扉の内側の板に何か刻まれている。',
        puzzle: 'q8',
      },
      {
        id: 'guest-libra',
        emoji: '⚖️',
        name: '天秤座の絵',
        x: 50,
        y: 34,
        text: '客室の壁に掛かった天秤座の絵。隅に博士の署名がある。星が 3つ描かれている。',
      },
      {
        id: 'guest-door',
        emoji: '🚪',
        name: '外階段への扉',
        x: 78,
        y: 28,
        text: '扉の外は雪の積もった外階段だ。',
      },
    ],
  },
  storage: {
    id: 'storage',
    name: '地下倉庫',
    floor: 'B1',
    map: { x: 0, y: 3 },
    description: '薪や道具をしまう地下の倉庫。冷たい空気がたまっている。',
    background: 'linear-gradient(180deg, #12161c 0%, #2e3640 55%, #2f2f33 56%, #18181b 100%)',
    exits: [{ dir: 'up', to: 'corridor', label: '廊下' }],
    hotspots: [
      {
        id: 'storage-panel',
        emoji: '⚡',
        name: '配電盤',
        x: 20,
        y: 40,
        text: '館の配電盤。1〜4番のブレーカーが並ぶ。今はすべて入っている。',
        puzzle: 'q9',
        concealed: true,
      },
      {
        id: 'storage-boots',
        emoji: '🥾',
        name: '乾燥棚の長靴',
        x: 78,
        y: 40,
        text: '乾燥棚に、名札付きの長靴が並んでいる。',
        evidence: 'soles',
      },
      {
        id: 'storage-wood',
        emoji: '🪵',
        name: '薪の山',
        x: 50,
        y: 36,
        text: '暖炉用の薪が積んである。',
      },
    ],
  },
  dome: {
    id: 'dome',
    name: '観測ドーム',
    floor: '屋上',
    map: { x: 2, y: 0 },
    description: '丸い天井の観測ドーム。中央に大望遠鏡が据えられている。',
    background: 'linear-gradient(180deg, #0b1226 0%, #1c2a4a 55%, #2a3550 56%, #141b2e 100%)',
    exits: [{ dir: 'down', to: 'guest', label: '客室' }],
    hotspots: [
      {
        id: 'dome-recorder',
        emoji: '📟',
        name: '記録装置',
        x: 20,
        y: 40,
        text: 'ドームの観測記録装置。止まったままだ。制御盤に星座の記号と 4桁の錠が並ぶ。',
        puzzle: 'q11',
      },
      {
        id: 'dome-telescope',
        emoji: '🔭',
        name: '大望遠鏡',
        x: 50,
        y: 34,
        text: 'ドームの中央に据えられた大望遠鏡。乾板は、ここの記録装置から消えた。',
        puzzle: 'q12',
      },
      {
        id: 'dome-window',
        emoji: '🪟',
        name: '外階段の窓',
        x: 80,
        y: 40,
        text: 'ドームの外階段へ出る扉の窓から、雪の積もった外階段を見下ろせる。',
        evidence: 'footprint',
      },
      {
        id: 'dome-brooch',
        emoji: '⭐',
        name: '床のブローチ',
        x: 20,
        y: 70,
        text: '床の隅で、何かが光っている。',
        evidence: 'brooch',
      },
    ],
  },
}
